// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzxtswvdfsesperqezci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6eHRzd3ZkZnNlc3BlcnFlemNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjQwMzAsImV4cCI6MjA2OTU0MDAzMH0.13p3fpz2hKLF-gBbUd6b5Ma7sU5MPE-jwo4tqCXfRPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
/**
 * Preconfigured Supabase client for database and auth operations.
 * Uses localStorage for session persistence.
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});